-- Partie 2
SELECT  TRANSACTIONS.CLIENT_ID
, SUM(CASE WHEN TRIM(PRODUCT_NOMENCLATURE.PRODUCT_TYPE) = 'MEUBLE' THEN TRANSACTIONS.PROD_PRICE*TRANSACTIONS.PROD_QTY
  ELSE 0
 END) AS VENTES_MEUBLE
, SUM(CASE WHEN TRIM(PRODUCT_NOMENCLATURE.PRODUCT_TYPE) = 'DECO' THEN TRANSACTIONS.PROD_PRICE*TRANSACTIONS.PROD_QTY
  ELSE 0
 END) AS VENTES_DECO
FROM TRANSACTIONS, PRODUCT_NOMENCLATURE
WHERE
     TRANSACTIONS.PROD_ID = PRODUCT_NOMENCLATURE.PRODUCT_ID
AND TRANSACTIONS.DATE BETWEEN DATE(2020,01,01) AND DATE(2020,12,31)
GROUP BY TRANSACTIONS.CLIENT_ID;
